name: Node.js Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - utils

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use the version of Node.js your project requires
          cache: "yarn"

      # Install dependencies
      - name: Install Dependencies
        working-directory: ${{ matrix.package }}
        run: yarn

      - name: Build
        working-directory: ${{ matrix.package }}
        run: yarn build

      - name: Publish to npm
        working-directory: ${{ matrix.package }}/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
